<!DOCTYPE html>
<html lang="en">

<head>

	<meta charset="utf-8">
	<title><?php echo $currentPage; ?></title>
	<link rel="stylesheet" href="css/styles.css">

</head>

<body class="container">
	<header>
		<a href="aacuna-main.php">
			<h1>Aacuna </h1>
			<img src="images/me.jpg" alt="Aacuna" align="right">
		</a>
	</header>

	<aside>
		<ul>
			<li>MAJOR</li>
			<li>Class of __</li>
			<li>FUN FACT</li>
		</ul>
	</aside>