<!DOCTYPE html>

<html lang="en">

<head>
	<meta charset="utf-8">
	<title><?php echo $currentPage; ?></title>
	<link rel="stylesheet" type="text/css" href="css/styles.css">
</head>
<body class="container">
	
	<header>
		<a href="anels28-main.php">
			<h1>Anels</h1>
			<img src="images/moi.jpg" alt="Moi" align="right">
		</a>
	</header>

	<aside>
		<ul>
			<li>Major</li>
			<li> FUn Fact</li>
			<li>Fun fact</li>
		</ul>
	</aside>